server:
  port: 8888
  
logging:
  level:
    net:
      pass:
        passSmishing:
          mapper: INFO
spring:
  application:
    nameMongo: Example
  data:
    mongodb:
      host: 192.168.1.235
      port: 27017
      database: mike_test
      repositories:
        type: auto
  devtools:
    livereload:
      enabled: true